version: '3.8'

services:
  backend:
    build: ./backend
    image: node-backend
    container_name: node-backend-container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: '1234'
      DB_NAME: shopdb
      DB_PORT: 3306
    restart: unless-stopped

  frontend:
    build: ./client
    image: shopease-frontend
    container_name: shopease-frontend-container
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
