name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHILMA_USERNAME }}
        password: ${{ secrets.DOCKERHILMA_PASSWORD }}

    - name: Build and push backend image
      run: |
        docker build -t hilma/node-backend:latest ./backend
        docker push hilma/node-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t hilma/shopease-frontend:latest ./client
        docker push hilma/shopease-frontend:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s/mysql-pvc.yaml
        kubectl apply -f ./k8s/mysql-deployment.yaml
        kubectl apply -f ./k8s/mysql-service.yaml
        kubectl apply -f ./k8s/backend-deployment.yaml
        kubectl apply -f ./k8s/backend-service.yaml
        kubectl apply -f ./k8s/frontend-deployment.yaml
        kubectl apply -f ./k8s/frontend-service.yaml
        kubectl rollout status deployment/backend-deployment
        kubectl rollout status deployment/frontend-deployment
